GET http://localhost:1323 HTTP/1.1
Accept: application/json

###

POST http://localhost:1323/request HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}